backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "main"
        label: "Main Content"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Quickstart Template"}
          - {label: "Subtitle", name: "subtitle", widget: "string", default: "This is a bare-bones Hugo project that has everything you need to quickly deploy it to Netlify"}
          - {label: "Deploy Button Text", name: "deploy_button_text", widget: "string", default: "Deploy to Netlify"}
          - {label: "View Repo Text", name: "view_repo_text", widget: "string", default: "View Repo"}
          - label: "Resource Links"
            name: "resources"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
